progressive_image:
    progressive_image:
        grid:
            framework: custom # Alebo ponechať prázdne
            columns: 16       # Vlastný počet stĺpcov
            layouts:
                desktop:
                    min_viewport: 1024
                    max_container: 1000
                mobile:
                    min_viewport: 0
                    max_container: ~ # Fluid (100vw)
        ratios:
            square: 1/1
            landscape: 16/9
            portrait: 3/4
            cinema: 21/9
            auto: ~

        generator: 'progressive_image.responsive_generator.liip_imagine'
    resolvers:
        my_path_resolver:
            type: "filesystem"
            roots: ['%kernel.project_dir%/public']
            allowUnresolvable: true
        my_asset_mapper_resolver:
            type: "asset_mapper"
        chain_resolver:
            type: "chain"
            resolvers:
                - 'my_path_resolver'
                - 'my_asset_mapper_resolver'
    driver: "gd" # alebo "imagick"
    loader: "progressive_image.filesystem.loader"
    resolver: "my_path_resolver"
    cache:  "app.cache.progressive_image"

    hash_resolution:
        width: 10
        height: 8
    fallback_image: "/images/placeholder.jpg"

    path_decorators:
        - "progressive_image.decorator.liip_imagine"
when@dev:
    progressive_image:
        resolver: chain