my_image_custom:
    resolvers:
        my_path_resolver:
            type: "filesystem"
            roots: ['%kernel.project_dir%/public']
            allowUnresolvable: true
        my_asset_mapper_resolver:
            type: "asset_mapper"
        chain_resolver:
            type: "chain"
            resolvers:
                - 'my_path_resolver'
                - 'my_asset_mapper_resolver'
    driver: "gd" # alebo "imagick"
    loader: "app.loader"
    resolver: "my_path_resolver"
    cache:  "app.cache.progressive_image"

    hash_resolution:
        width: 10
        height: 8
    fallback_image: "/images/placeholder.jpg"

    path_decorators:
        - "app.handler.LiipPathHandler"
when@dev:
    my_image_custom:
        resolver: chain